# All config data
logo: assets/images/uc_logo.png
title: UpstreamChallenge
grid_section_id: about
grid_section_name: About
#featured_section_id: featuredId
#featured_section_name: Featured
form_section_id: formId
form_section_name: Form
#album_section_id: albumId
#album_section_name: Album
#book_section_id: bookId
#book_section_name: book

# Exclude metadata and development time dependencies
exclude: [README.md, LICENSE]
